#!/bin/bash
#
# git-hook-setup.sh - Install git hooks for the monorepo
#
# Usage:
#   .bin/git-hook-setup.sh              # Install all hooks
#   .bin/git-hook-setup.sh --remove     # Remove all hooks
#   .bin/git-hook-setup.sh --strict     # Install with strict secret scanning
#   .bin/git-hook-setup.sh --no-secrets # Install without secret scanning
#   .bin/git-hook-setup.sh --no-lint    # Install without Python linting
#   .bin/git-hook-setup.sh --no-gitmodules-sync  # Install without gitmodules orphan check
#   .bin/git-hook-setup.sh --no-dep-lint         # Install without pyproject.toml build lint
#
# Hooks installed:
#   - pre-commit:
#       1. Secret scanning (blocks real secrets, warns on mock secrets)
#       2. Updates COMMIT file with parent hash
#       3. Checks package dirs sync with pyproject.toml (packages_py/, polyglot/, fastapi_apps/, fastapi_server/)
#       4. Python linting (ruff + py_compile on staged .py files)
#       5. ESLint ban check (prevents ESLint usage - project uses Biome)
#       6. Submodule commit check (ensures referenced commits exist on remotes)
#       7. Gitmodules orphan pruning (auto-removes entries with no gitlink)
#       8. pyproject.toml build config lint (hatchling + explicit packages)
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
HOOKS_DIR="$ROOT_DIR/.git/hooks"

# Options
STRICT_MODE=false
ENABLE_SECRETS=true
ENABLE_PYTHON_LINT=true
ENABLE_ESLINT_BAN=true
ENABLE_SUBMODULE_CHECK=true
ENABLE_GITMODULES_SYNC=true
ENABLE_DEP_LINT=true

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

install_hooks() {
    log_info "Installing git hooks..."

    # Ensure hooks directory exists
    mkdir -p "$HOOKS_DIR"

    # Build secret scanner options
    SECRET_SCANNER_OPTS="--staged"
    if [ "$STRICT_MODE" = true ]; then
        SECRET_SCANNER_OPTS="$SECRET_SCANNER_OPTS --strict"
    fi

    # Create pre-commit hook
    cat > "$HOOKS_DIR/pre-commit" << 'HOOK_HEADER'
#!/bin/bash
#
# Pre-commit hook: Multiple checks
#
# 1. Secret scanning (blocks real secrets, warns on mock secrets)
# 2. Update COMMIT file with parent (HEAD) commit hash
# 3. Ensure packages_py/ changes are reflected in pyproject.toml
#
# Generated by: .bin/git-hook-setup.sh
# To bypass (not recommended): git commit --no-verify
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$(dirname "$SCRIPT_DIR")")"

# Initialize pyenv if available (needed for ruff)
# Try multiple locations for GitHub Desktop compatibility
USER_HOME="${HOME:-$(eval echo ~$(whoami))}"
for pyenv_dir in "$USER_HOME/.pyenv" "$PYENV_ROOT"; do
    if [ -d "$pyenv_dir" ]; then
        export PYENV_ROOT="$pyenv_dir"
        export PATH="$PYENV_ROOT/bin:$PYENV_ROOT/shims:$PATH"
        break
    fi
done

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

HOOK_HEADER

    # Add secret scanning section conditionally
    if [ "$ENABLE_SECRETS" = true ]; then
        cat >> "$HOOKS_DIR/pre-commit" << HOOK_SECRETS
# =============================================================================
# STEP 1: Secret Scanning
# =============================================================================
# Scans staged files for secrets, API keys, and tokens before commit.
# - Real secrets: Always block commit
# - Mock/example secrets: Warn (or block in strict mode)

SECRET_SCANNER="\$ROOT_DIR/.bin/scan-secrets.sh"
SECRET_SCANNER_OPTS="$SECRET_SCANNER_OPTS"

if [[ -f "\$SECRET_SCANNER" ]]; then
    # Make scanner executable if needed
    [[ ! -x "\$SECRET_SCANNER" ]] && chmod +x "\$SECRET_SCANNER"

    echo ""
    echo -e "\${GREEN}[pre-commit]\${NC} Scanning for secrets..."

    if ! "\$SECRET_SCANNER" \$SECRET_SCANNER_OPTS; then
        exit_code=\$?
        echo ""
        echo -e "\${RED}=========================================="
        echo "COMMIT BLOCKED: Secrets detected!"
        echo "==========================================${NC}"
        echo ""
        echo "Options:"
        echo "  1. Remove the detected secrets and try again"
        echo "  2. Add false positives to .secrets-allowlist"
        echo "  3. View details: .bin/scan-secrets.sh --staged"
        echo "  4. Interactive: .bin/scan-secrets.sh --staged --fix"
        echo "  5. Bypass (NOT recommended): git commit --no-verify"
        echo ""
        exit \$exit_code
    fi
else
    echo -e "\${YELLOW}[pre-commit]\${NC} Warning: Secret scanner not found, skipping"
fi

HOOK_SECRETS
    fi

    # Add the rest of the hook
    cat >> "$HOOKS_DIR/pre-commit" << 'HOOK_BODY'
# =============================================================================
# STEP 2: Update COMMIT file with parent hash
# =============================================================================
# This updates the COMMIT file with the current HEAD hash (which becomes the
# parent of the new commit). The COMMIT file is auto-staged.
# Location: common/config/COMMIT (alongside YAML config files)

COMMIT_FILE="${ROOT_DIR}/common/config/COMMIT"

# Get current HEAD hash (this will be the parent of the new commit)
PARENT_HASH="$(git rev-parse HEAD 2>/dev/null || echo 'initial')"

# Check if COMMIT file exists and has the current hash
UPDATE_COMMIT=true
if [ -f "${COMMIT_FILE}" ]; then
    EXISTING_HASH="$(cat "${COMMIT_FILE}" | tr -d '[:space:]')"
    if [ "${EXISTING_HASH}" = "${PARENT_HASH}" ]; then
        UPDATE_COMMIT=false
    fi
fi

if [ "$UPDATE_COMMIT" = true ]; then
    echo "${PARENT_HASH}" > "${COMMIT_FILE}"
    git add "${COMMIT_FILE}"
    echo -e "${GREEN}[pre-commit]${NC} Updated COMMIT file with parent hash: ${PARENT_HASH:0:8}"
fi

# =============================================================================
# STEP 3: Check packages_py/ sync with pyproject.toml
# =============================================================================

SYNC_SCRIPT="$ROOT_DIR/.bin/pyproject-sync-pkg-repo.py"
if [[ ! -f "$SYNC_SCRIPT" ]]; then
    echo -e "${YELLOW}[pre-commit]${NC} Warning: .bin/pyproject-sync-pkg-repo.py not found, skipping package sync"
    exit 0
fi

# Check if any package dirs are staged (packages_py/, polyglot/, fastapi_apps/, fastapi_server/)
if git diff --cached --name-only | grep -qE "^(packages_py|polyglot|fastapi_apps|fastapi_server)/"; then
    echo -e "${GREEN}[pre-commit]${NC} Detected package changes, checking pyproject.toml sync..."

    # Run sync in dry-run mode to check
    OUTPUT=$(python3 "$SYNC_SCRIPT" --dry-run 2>&1)

    if echo "$OUTPUT" | grep -q "DRY RUN:"; then
        echo ""
        echo -e "${RED}=========================================="
        echo "pyproject.toml needs to be updated!"
        echo "==========================================${NC}"
        echo ""
        echo "Run the following command to sync:"
        echo "  python .bin/pyproject-sync-pkg-repo.py"
        echo ""
        echo "Then add the changes:"
        echo "  git add pyproject.toml fastapi_server/pyproject.toml"
        echo ""
        exit 1
    fi
fi

HOOK_BODY

    # Add Python linting section conditionally
    if [ "$ENABLE_PYTHON_LINT" = true ]; then
        cat >> "$HOOKS_DIR/pre-commit" << 'HOOK_PYTHON_LINT'
# =============================================================================
# STEP 4: Python Linting (staged .py files only)
# =============================================================================
# Runs ruff linter and py_compile on staged Python files.
# Only checks files in packages_py/ that are part of this commit.

PYTHON_LINTER="$ROOT_DIR/.bin/python-linting.py"

# Get staged Python files in packages_py/
STAGED_PY_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep "^packages_py/.*\.py$" | grep -v "__pycache__" | grep -v "\.venv" || true)

if [[ -n "$STAGED_PY_FILES" ]]; then
    echo ""
    echo -e "${GREEN}[pre-commit]${NC} Linting staged Python files..."

    if [[ -f "$PYTHON_LINTER" ]]; then
        # Create temp directory for staged files
        LINT_FAILED=false

        # Check each staged file with ruff
        for py_file in $STAGED_PY_FILES; do
            if [[ -f "$py_file" ]]; then
                # Syntax check
                if ! python3 -m py_compile "$py_file" 2>/dev/null; then
                    echo -e "${RED}[pre-commit]${NC} Syntax error in: $py_file"
                    LINT_FAILED=true
                fi
            fi
        done

        # Run ruff on all staged Python files (if any exist)
        EXISTING_FILES=""
        for py_file in $STAGED_PY_FILES; do
            if [[ -f "$py_file" ]]; then
                EXISTING_FILES="$EXISTING_FILES $py_file"
            fi
        done

        if [[ -n "$EXISTING_FILES" ]]; then
            # Find ruff: use direct path to avoid pyenv shim issues
            RUFF_CMD=""
            USER_HOME="${HOME:-$(eval echo ~$(whoami))}"
            for ruff_path in "$USER_HOME/.pyenv/versions/3.11.0/bin/ruff" "$USER_HOME/.pyenv/versions/3.12.0/bin/ruff" "$USER_HOME/.local/bin/ruff"; do
                if [[ -x "$ruff_path" ]]; then
                    RUFF_CMD="$ruff_path"
                    break
                fi
            done
            if [[ -z "$RUFF_CMD" ]]; then
                RUFF_CMD="ruff"  # fallback to PATH
            fi
            RUFF_OUTPUT=$($RUFF_CMD check --ignore E501,F401,F811,F403,E402 $EXISTING_FILES 2>&1 || true)
            if [[ -n "$RUFF_OUTPUT" ]] && ! echo "$RUFF_OUTPUT" | grep -q "All checks passed"; then
                echo ""
                echo -e "${RED}[pre-commit]${NC} Ruff linting errors found:"
                echo "$RUFF_OUTPUT" | head -20
                if [[ $(echo "$RUFF_OUTPUT" | wc -l) -gt 20 ]]; then
                    echo "  ... (truncated, run 'ruff check' for full output)"
                fi
                LINT_FAILED=true
            fi
        fi

        if [ "$LINT_FAILED" = true ]; then
            echo ""
            echo -e "${RED}=========================================="
            echo "COMMIT BLOCKED: Python linting errors!"
            echo "==========================================${NC}"
            echo ""
            echo "Options:"
            echo "  1. Fix the linting errors and try again"
            echo "  2. Auto-fix: python3 .bin/python-linting.py --fix"
            echo "  3. Check all: python3 .bin/python-linting.py"
            echo "  4. Bypass (NOT recommended): git commit --no-verify"
            echo ""
            exit 1
        fi

        echo -e "${GREEN}[pre-commit]${NC} Python linting passed ($(echo $STAGED_PY_FILES | wc -w | tr -d ' ') files)"
    else
        echo -e "${YELLOW}[pre-commit]${NC} Warning: Python linter not found, skipping"
    fi
fi

HOOK_PYTHON_LINT
    fi

    # Add ESLint ban check section conditionally
    if [ "$ENABLE_ESLINT_BAN" = true ]; then
        cat >> "$HOOKS_DIR/pre-commit" << 'HOOK_ESLINT_BAN'
# =============================================================================
# STEP 5: ESLint Ban Check
# =============================================================================
# This project uses Biome for linting. ESLint is not allowed.
# Checks for:
# - ESLint config files (.eslintrc*, eslint.config.*)
# - ESLint dependencies in package.json files
# Excludes: node_modules, __testcases__

ESLINT_BAN_FAILED=false

# Check for staged ESLint config files (excluding node_modules and __testcases__)
STAGED_ESLINT_CONFIGS=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\.eslintrc|eslint\.config\." | grep -v "node_modules" | grep -v "__testcases__" || true)

if [[ -n "$STAGED_ESLINT_CONFIGS" ]]; then
    echo ""
    echo -e "${RED}[pre-commit]${NC} ESLint config files detected in staged changes:"
    for config_file in $STAGED_ESLINT_CONFIGS; do
        echo "  - $config_file"
    done
    ESLINT_BAN_FAILED=true
fi

# Check for ESLint dependencies in staged package.json files (excluding node_modules and __testcases__)
STAGED_PACKAGE_JSON=$(git diff --cached --name-only --diff-filter=ACM | grep "package\.json$" | grep -v "node_modules" | grep -v "__testcases__" || true)

if [[ -n "$STAGED_PACKAGE_JSON" ]]; then
    for pkg_file in $STAGED_PACKAGE_JSON; do
        if [[ -f "$pkg_file" ]]; then
            # Check for eslint dependencies in the staged version
            ESLINT_DEPS=$(git show ":$pkg_file" 2>/dev/null | grep -E '"eslint|"@typescript-eslint|"eslint-plugin-|"@eslint/' | grep -v "// eslint" || true)
            if [[ -n "$ESLINT_DEPS" ]]; then
                echo ""
                echo -e "${RED}[pre-commit]${NC} ESLint dependencies found in $pkg_file:"
                echo "$ESLINT_DEPS" | head -10
                ESLINT_BAN_FAILED=true
            fi
        fi
    done
fi

if [ "$ESLINT_BAN_FAILED" = true ]; then
    echo ""
    echo -e "${RED}=========================================="
    echo "COMMIT BLOCKED: ESLint usage detected!"
    echo "==========================================${NC}"
    echo ""
    echo "This project uses Biome for linting, not ESLint."
    echo ""
    echo "To fix:"
    echo "  1. Remove ESLint config files (.eslintrc*, eslint.config.*)"
    echo "  2. Remove ESLint dependencies from package.json:"
    echo "     - eslint"
    echo "     - @typescript-eslint/*"
    echo "     - eslint-plugin-*"
    echo "     - @eslint/*"
    echo "  3. Update lint scripts to use: biome lint"
    echo ""
    echo "Bypass (NOT recommended): git commit --no-verify"
    echo ""
    exit 1
fi

echo -e "${GREEN}[pre-commit]${NC} ESLint ban check passed"

HOOK_ESLINT_BAN
    fi

    # Add submodule commit check section conditionally
    if [ "$ENABLE_SUBMODULE_CHECK" = true ]; then
        cat >> "$HOOKS_DIR/pre-commit" << 'HOOK_SUBMODULE_CHECK'
# =============================================================================
# STEP 6: Submodule Commit Check
# =============================================================================
# Ensures that any staged submodule pointer changes reference commits that
# actually exist on the submodule's remote. Without this, cloning on another
# machine fails with: "a submodule points to a commit which does not exist"

SUBMODULE_CHECKER="$ROOT_DIR/.bin/check-submodule-commits.sh"

# Check if any submodule paths are staged
STAGED_SUBMODULES=""
if [[ -f "$ROOT_DIR/.gitmodules" ]]; then
    while IFS= read -r sm_line; do
        sm_path=$(echo "$sm_line" | sed 's/.*path = //')
        if git diff --cached --name-only | grep -q "^${sm_path}$"; then
            STAGED_SUBMODULES="$STAGED_SUBMODULES $sm_path"
        fi
    done < <(grep 'path = ' "$ROOT_DIR/.gitmodules")
fi

if [[ -n "$STAGED_SUBMODULES" ]]; then
    echo ""
    echo -e "${GREEN}[pre-commit]${NC} Checking submodule commits exist on remotes..."

    if [[ -f "$SUBMODULE_CHECKER" && -x "$SUBMODULE_CHECKER" ]]; then
        if ! "$SUBMODULE_CHECKER"; then
            echo ""
            echo -e "${RED}=========================================="
            echo "COMMIT BLOCKED: Submodule commit not on remote!"
            echo "==========================================${NC}"
            echo ""
            echo "One or more submodules reference commits that haven't been"
            echo "pushed to their remotes. This will break clones on other machines."
            echo ""
            echo "Options:"
            echo "  1. Push the submodule: cd <submodule> && git push"
            echo "  2. Check details: .bin/check-submodule-commits.sh --all --verbose"
            echo "  3. Bypass (NOT recommended): git commit --no-verify"
            echo ""
            exit 1
        fi
        echo -e "${GREEN}[pre-commit]${NC} Submodule commits verified on remotes"
    else
        echo -e "${YELLOW}[pre-commit]${NC} Warning: Submodule checker not found or not executable, skipping"
    fi
fi

HOOK_SUBMODULE_CHECK
    fi

    # Add gitmodules orphan check section conditionally
    if [ "$ENABLE_GITMODULES_SYNC" = true ]; then
        cat >> "$HOOKS_DIR/pre-commit" << 'HOOK_GITMODULES_SYNC'
# =============================================================================
# STEP 7: Gitmodules Orphan Pruning
# =============================================================================
# Prunes orphaned entries from .gitmodules — submodule definitions with no
# matching gitlink (mode 160000) in the index. Orphans cause GitHub Desktop
# clone failures. Runs automatically and stages the cleaned .gitmodules.

GITMODULES_SYNC="$ROOT_DIR/.bin/sync-gitmodules.sh"

if [[ -f "$ROOT_DIR/.gitmodules" && -f "$GITMODULES_SYNC" && -x "$GITMODULES_SYNC" ]]; then
    "$GITMODULES_SYNC" --verbose
fi

HOOK_GITMODULES_SYNC
    fi

    # Add pyproject.toml build config lint section conditionally
    if [ "$ENABLE_DEP_LINT" = true ]; then
        cat >> "$HOOKS_DIR/pre-commit" << 'HOOK_DEP_LINT'
# =============================================================================
# STEP 8: pyproject.toml Build Config Lint
# =============================================================================
# Validates that staged pyproject.toml files use hatchling with explicit
# packages. Setuptools auto-discovery can silently produce empty wheels,
# causing ModuleNotFoundError in cloud deployments.

DEP_LINT_SCRIPT="$ROOT_DIR/.bin/python_lint_dep_find.py"

# Check if any pyproject.toml files are staged
STAGED_PYPROJECTS=$(git diff --cached --name-only --diff-filter=ACM | grep "pyproject\.toml$" || true)

if [[ -n "$STAGED_PYPROJECTS" ]]; then
    echo ""
    echo -e "${GREEN}[pre-commit]${NC} Checking pyproject.toml build configs..."

    if [[ -f "$DEP_LINT_SCRIPT" ]]; then
        if ! python3 "$DEP_LINT_SCRIPT" --staged; then
            echo ""
            echo -e "${RED}=========================================="
            echo "COMMIT BLOCKED: pyproject.toml build config issue!"
            echo "==========================================${NC}"
            echo ""
            echo "Options:"
            echo "  1. Fix the build config (migrate to hatchling with explicit packages)"
            echo "  2. Check all: python3 .bin/python_lint_dep_find.py --verbose"
            echo "  3. Bypass (NOT recommended): git commit --no-verify"
            echo ""
            exit 1
        fi
        echo -e "${GREEN}[pre-commit]${NC} pyproject.toml build configs valid"
    else
        echo -e "${YELLOW}[pre-commit]${NC} Warning: python_lint_dep_find.py not found, skipping"
    fi
fi

HOOK_DEP_LINT
    fi

    # Add final success message
    cat >> "$HOOKS_DIR/pre-commit" << 'HOOK_FOOTER'
echo -e "${GREEN}[pre-commit]${NC} All checks passed!"
exit 0
HOOK_FOOTER

    chmod +x "$HOOKS_DIR/pre-commit"
    log_info "Installed pre-commit hook"

    # Remove old hooks if they exist (from previous versions)
    for old_hook in pre-push post-commit; do
        if [ -f "$HOOKS_DIR/$old_hook" ]; then
            rm "$HOOKS_DIR/$old_hook"
            log_info "Removed old $old_hook hook"
        fi
    done

    log_info "Git hooks installed successfully!"
    echo ""
    echo "Installed hooks:"
    echo "  - pre-commit:"
    if [ "$ENABLE_SECRETS" = true ]; then
        if [ "$STRICT_MODE" = true ]; then
            echo "      1. Secret scanning (STRICT: blocks real AND mock secrets)"
        else
            echo "      1. Secret scanning (blocks real secrets, warns on mock)"
        fi
    else
        echo "      1. Secret scanning: DISABLED"
    fi
    echo "      2. Updates COMMIT file with parent hash (auto-staged)"
    echo "      3. Checks package dirs sync with pyproject.toml (pyproject-sync-pkg-repo.py)"
    if [ "$ENABLE_PYTHON_LINT" = true ]; then
        echo "      4. Python linting (ruff + py_compile on staged .py files)"
    else
        echo "      4. Python linting: DISABLED"
    fi
    if [ "$ENABLE_ESLINT_BAN" = true ]; then
        echo "      5. ESLint ban check (project uses Biome instead)"
    else
        echo "      5. ESLint ban check: DISABLED"
    fi
    if [ "$ENABLE_SUBMODULE_CHECK" = true ]; then
        echo "      6. Submodule commit check (verifies commits exist on remotes)"
    else
        echo "      6. Submodule commit check: DISABLED"
    fi
    if [ "$ENABLE_GITMODULES_SYNC" = true ]; then
        echo "      7. Gitmodules orphan pruning (auto-removes orphaned entries)"
    else
        echo "      7. Gitmodules orphan check: DISABLED"
    fi
    if [ "$ENABLE_DEP_LINT" = true ]; then
        echo "      8. pyproject.toml build config lint (hatchling + explicit packages)"
    else
        echo "      8. pyproject.toml build config lint: DISABLED"
    fi
    echo ""
    echo "To test secret scanner:       .bin/scan-secrets.sh --staged"
    echo "To test Python linting:       python3 .bin/python-linting.py"
    echo "To test build config lint:    python3 .bin/python_lint_dep_find.py --verbose"
    echo "To test submodule commits:    .bin/check-submodule-commits.sh --all --verbose"
    echo "To test gitmodules sync:      .bin/sync-gitmodules.sh --check --verbose"
    echo "To reinstall hooks:           .bin/git-hook-setup.sh"
}

remove_hooks() {
    log_info "Removing git hooks..."

    if [[ -f "$HOOKS_DIR/pre-commit" ]]; then
        rm "$HOOKS_DIR/pre-commit"
        log_info "Removed pre-commit hook"
    else
        log_warn "pre-commit hook not found"
    fi

    log_info "Git hooks removed successfully!"
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --remove|-r)
            remove_hooks
            exit 0
            ;;
        --strict)
            STRICT_MODE=true
            shift
            ;;
        --no-secrets)
            ENABLE_SECRETS=false
            shift
            ;;
        --no-lint)
            ENABLE_PYTHON_LINT=false
            shift
            ;;
        --no-eslint-ban)
            ENABLE_ESLINT_BAN=false
            shift
            ;;
        --no-submodule-check)
            ENABLE_SUBMODULE_CHECK=false
            shift
            ;;
        --no-gitmodules-sync)
            ENABLE_GITMODULES_SYNC=false
            shift
            ;;
        --no-dep-lint)
            ENABLE_DEP_LINT=false
            shift
            ;;
        --help|-h)
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --remove, -r   Remove installed hooks"
            echo "  --strict       Enable strict mode (block mock secrets too)"
            echo "  --no-secrets   Disable secret scanning"
            echo "  --no-lint      Disable Python linting"
            echo "  --no-eslint-ban      Disable ESLint ban check"
            echo "  --no-submodule-check   Disable submodule commit check"
            echo "  --no-gitmodules-sync   Disable gitmodules orphan pruning"
            echo "  --no-dep-lint          Disable pyproject.toml build config lint"
            echo "  --help, -h             Show this help message"
            echo ""
            echo "Examples:"
            echo "  $0                # Install with all checks enabled"
            echo "  $0 --strict       # Install with strict secret scanning"
            echo "  $0 --no-secrets   # Install without secret scanning"
            echo "  $0 --no-lint      # Install without Python linting"
            echo "  $0 --remove       # Uninstall hooks"
            echo ""
            echo "Secret Scanner:"
            echo "  Test:        .bin/scan-secrets.sh --staged"
            echo "  Full scan:   .bin/scan-secrets.sh --all"
            echo "  Interactive: .bin/scan-secrets.sh --staged --fix"
            echo ""
            echo "Python Linter:"
            echo "  Test:        python3 .bin/python-linting.py"
            echo "  Auto-fix:    python3 .bin/python-linting.py --fix"
            echo "  Verbose:     python3 .bin/python-linting.py -v"
            echo ""
            echo "Build Config Lint:"
            echo "  Test:        python3 .bin/python_lint_dep_find.py"
            echo "  Verbose:     python3 .bin/python_lint_dep_find.py --verbose"
            exit 0
            ;;
        *)
            log_error "Unknown option: $1"
            echo "Use --help for usage information"
            exit 1
            ;;
    esac
done

# Default action: install hooks
install_hooks
