import { createRoot } from 'react-dom/client';
import './styles.css';
import { FigmaTokenExporter } from '../src';
import type { PrimitiveToken, SemanticToken, ComponentToken, VersionEntry } from '../src';

const PRIMITIVES: PrimitiveToken[] = [
  { id: 'p.blue.50', name: 'blue.50', group: 'blue', value: { '*': '#eff6ff' }, type: 'color' },
  { id: 'p.blue.100', name: 'blue.100', group: 'blue', value: { '*': '#dbeafe' }, type: 'color' },
  { id: 'p.blue.200', name: 'blue.200', group: 'blue', value: { '*': '#bfdbfe' }, type: 'color' },
  { id: 'p.blue.300', name: 'blue.300', group: 'blue', value: { '*': '#93c5fd' }, type: 'color' },
  { id: 'p.blue.400', name: 'blue.400', group: 'blue', value: { '*': '#60a5fa' }, type: 'color' },
  { id: 'p.blue.500', name: 'blue.500', group: 'blue', value: { '*': '#3b82f6' }, type: 'color' },
  { id: 'p.blue.600', name: 'blue.600', group: 'blue', value: { '*': '#2563eb' }, type: 'color' },
  { id: 'p.blue.700', name: 'blue.700', group: 'blue', value: { '*': '#1d4ed8' }, type: 'color' },
  { id: 'p.blue.800', name: 'blue.800', group: 'blue', value: { '*': '#1e40af' }, type: 'color' },
  { id: 'p.blue.900', name: 'blue.900', group: 'blue', value: { '*': '#1e3a8a' }, type: 'color' },
  { id: 'p.slate.50', name: 'slate.50', group: 'slate', value: { '*': '#f8fafc' }, type: 'color' },
  { id: 'p.slate.100', name: 'slate.100', group: 'slate', value: { '*': '#f1f5f9' }, type: 'color' },
  { id: 'p.slate.200', name: 'slate.200', group: 'slate', value: { '*': '#e2e8f0' }, type: 'color' },
  { id: 'p.slate.300', name: 'slate.300', group: 'slate', value: { '*': '#cbd5e1' }, type: 'color' },
  { id: 'p.slate.400', name: 'slate.400', group: 'slate', value: { '*': '#94a3b8' }, type: 'color' },
  { id: 'p.slate.500', name: 'slate.500', group: 'slate', value: { '*': '#64748b' }, type: 'color' },
  { id: 'p.slate.600', name: 'slate.600', group: 'slate', value: { '*': '#475569' }, type: 'color' },
  { id: 'p.slate.700', name: 'slate.700', group: 'slate', value: { '*': '#334155' }, type: 'color' },
  { id: 'p.slate.800', name: 'slate.800', group: 'slate', value: { '*': '#1e293b' }, type: 'color' },
  { id: 'p.slate.900', name: 'slate.900', group: 'slate', value: { '*': '#0f172a' }, type: 'color' },
  { id: 'p.red.400', name: 'red.400', group: 'red', value: { '*': '#f87171' }, type: 'color' },
  { id: 'p.red.500', name: 'red.500', group: 'red', value: { '*': '#ef4444' }, type: 'color' },
  { id: 'p.red.600', name: 'red.600', group: 'red', value: { '*': '#dc2626' }, type: 'color' },
  { id: 'p.green.400', name: 'green.400', group: 'green', value: { '*': '#4ade80' }, type: 'color' },
  { id: 'p.green.500', name: 'green.500', group: 'green', value: { '*': '#22c55e' }, type: 'color' },
  { id: 'p.green.600', name: 'green.600', group: 'green', value: { '*': '#16a34a' }, type: 'color' },
  { id: 'p.amber.400', name: 'amber.400', group: 'amber', value: { '*': '#fbbf24' }, type: 'color' },
  { id: 'p.amber.500', name: 'amber.500', group: 'amber', value: { '*': '#f59e0b' }, type: 'color' },
  { id: 'p.white', name: 'white', group: 'neutral', value: { '*': '#ffffff' }, type: 'color' },
  { id: 'p.black', name: 'black', group: 'neutral', value: { '*': '#000000' }, type: 'color' },
  { id: 'p.transparent', name: 'transparent', group: 'neutral', value: { '*': 'transparent' }, type: 'color' },
  { id: 'p.spacing.0', name: 'spacing.0', group: 'spacing', value: { '*': '0px' }, type: 'spacing' },
  { id: 'p.spacing.1', name: 'spacing.1', group: 'spacing', value: { '*': '4px' }, type: 'spacing' },
  { id: 'p.spacing.2', name: 'spacing.2', group: 'spacing', value: { '*': '8px' }, type: 'spacing' },
  { id: 'p.spacing.3', name: 'spacing.3', group: 'spacing', value: { '*': '12px' }, type: 'spacing' },
  { id: 'p.spacing.4', name: 'spacing.4', group: 'spacing', value: { '*': '16px' }, type: 'spacing' },
  { id: 'p.spacing.5', name: 'spacing.5', group: 'spacing', value: { '*': '20px' }, type: 'spacing' },
  { id: 'p.spacing.6', name: 'spacing.6', group: 'spacing', value: { '*': '24px' }, type: 'spacing' },
  { id: 'p.spacing.8', name: 'spacing.8', group: 'spacing', value: { '*': '32px' }, type: 'spacing' },
  { id: 'p.radius.none', name: 'radius.none', group: 'radius', value: { '*': '0px' }, type: 'radius' },
  { id: 'p.radius.sm', name: 'radius.sm', group: 'radius', value: { '*': '4px' }, type: 'radius' },
  { id: 'p.radius.md', name: 'radius.md', group: 'radius', value: { '*': '8px' }, type: 'radius' },
  { id: 'p.radius.lg', name: 'radius.lg', group: 'radius', value: { '*': '12px' }, type: 'radius' },
  { id: 'p.radius.full', name: 'radius.full', group: 'radius', value: { '*': '9999px' }, type: 'radius' },
  { id: 'p.fontSize.xs', name: 'fontSize.xs', group: 'fontSize', value: { Web: '12px', iOS: '11px', Android: '12sp' }, type: 'fontSize' },
  { id: 'p.fontSize.sm', name: 'fontSize.sm', group: 'fontSize', value: { Web: '14px', iOS: '13px', Android: '14sp' }, type: 'fontSize' },
  { id: 'p.fontSize.base', name: 'fontSize.base', group: 'fontSize', value: { Web: '16px', iOS: '15px', Android: '16sp' }, type: 'fontSize' },
  { id: 'p.fontSize.lg', name: 'fontSize.lg', group: 'fontSize', value: { Web: '18px', iOS: '17px', Android: '18sp' }, type: 'fontSize' },
];

const SEMANTICS: SemanticToken[] = [
  { id: 's.surface.primary', name: 'surface.primary', cat: 'surface', ref: { Light: 'p.white', Dark: 'p.slate.900' }, type: 'color' },
  { id: 's.surface.secondary', name: 'surface.secondary', cat: 'surface', ref: { Light: 'p.slate.50', Dark: 'p.slate.800' }, type: 'color' },
  { id: 's.surface.tertiary', name: 'surface.tertiary', cat: 'surface', ref: { Light: 'p.slate.100', Dark: 'p.slate.700' }, type: 'color' },
  { id: 's.surface.inverse', name: 'surface.inverse', cat: 'surface', ref: { Light: 'p.slate.900', Dark: 'p.white' }, type: 'color' },
  { id: 's.text.primary', name: 'text.primary', cat: 'text', ref: { Light: 'p.slate.900', Dark: 'p.slate.50' }, type: 'color' },
  { id: 's.text.secondary', name: 'text.secondary', cat: 'text', ref: { Light: 'p.slate.600', Dark: 'p.slate.400' }, type: 'color' },
  { id: 's.text.tertiary', name: 'text.tertiary', cat: 'text', ref: { Light: 'p.slate.400', Dark: 'p.slate.500' }, type: 'color' },
  { id: 's.text.inverse', name: 'text.inverse', cat: 'text', ref: { Light: 'p.white', Dark: 'p.slate.900' }, type: 'color' },
  { id: 's.text.link', name: 'text.link', cat: 'text', ref: { Light: 'p.blue.600', Dark: 'p.blue.400' }, type: 'color' },
  { id: 's.border.default', name: 'border.default', cat: 'border', ref: { Light: 'p.slate.200', Dark: 'p.slate.700' }, type: 'color' },
  { id: 's.border.strong', name: 'border.strong', cat: 'border', ref: { Light: 'p.slate.300', Dark: 'p.slate.600' }, type: 'color' },
  { id: 's.border.focus', name: 'border.focus', cat: 'border', ref: { Light: 'p.blue.500', Dark: 'p.blue.400' }, type: 'color' },
  { id: 's.interactive.primary', name: 'interactive.primary', cat: 'interactive', ref: { Light: 'p.blue.600', Dark: 'p.blue.500' }, type: 'color' },
  { id: 's.interactive.primaryHover', name: 'interactive.primaryHover', cat: 'interactive', ref: { Light: 'p.blue.700', Dark: 'p.blue.400' }, type: 'color' },
  { id: 's.interactive.danger', name: 'interactive.danger', cat: 'interactive', ref: { Light: 'p.red.600', Dark: 'p.red.500' }, type: 'color' },
  { id: 's.interactive.dangerHover', name: 'interactive.dangerHover', cat: 'interactive', ref: { Light: 'p.red.500', Dark: 'p.red.400' }, type: 'color' },
  { id: 's.interactive.success', name: 'interactive.success', cat: 'interactive', ref: { Light: 'p.green.600', Dark: 'p.green.500' }, type: 'color' },
  { id: 's.interactive.warning', name: 'interactive.warning', cat: 'interactive', ref: { Light: 'p.amber.500', Dark: 'p.amber.400' }, type: 'color' },
  { id: 's.gap.xs', name: 'gap.xs', cat: 'spacing', ref: { '*': 'p.spacing.1' }, type: 'spacing' },
  { id: 's.gap.sm', name: 'gap.sm', cat: 'spacing', ref: { '*': 'p.spacing.2' }, type: 'spacing' },
  { id: 's.gap.md', name: 'gap.md', cat: 'spacing', ref: { '*': 'p.spacing.3' }, type: 'spacing' },
  { id: 's.gap.lg', name: 'gap.lg', cat: 'spacing', ref: { '*': 'p.spacing.4' }, type: 'spacing' },
  { id: 's.gap.xl', name: 'gap.xl', cat: 'spacing', ref: { '*': 'p.spacing.6' }, type: 'spacing' },
  { id: 's.padding.card', name: 'padding.card', cat: 'spacing', ref: { '*': 'p.spacing.4' }, type: 'spacing' },
  { id: 's.padding.page', name: 'padding.page', cat: 'spacing', ref: { '*': 'p.spacing.6' }, type: 'spacing' },
  { id: 's.radius.control', name: 'radius.control', cat: 'radius', ref: { '*': 'p.radius.md' }, type: 'radius' },
  { id: 's.radius.card', name: 'radius.card', cat: 'radius', ref: { '*': 'p.radius.lg' }, type: 'radius' },
  { id: 's.radius.pill', name: 'radius.pill', cat: 'radius', ref: { '*': 'p.radius.full' }, type: 'radius' },
  { id: 's.fontSize.body', name: 'fontSize.body', cat: 'typography', ref: { '*': 'p.fontSize.base' }, type: 'fontSize' },
  { id: 's.fontSize.caption', name: 'fontSize.caption', cat: 'typography', ref: { '*': 'p.fontSize.xs' }, type: 'fontSize' },
  { id: 's.fontSize.label', name: 'fontSize.label', cat: 'typography', ref: { '*': 'p.fontSize.sm' }, type: 'fontSize' },
];

const COMPONENTS: ComponentToken[] = [
  { id: 'c.btn.primary.bg', name: 'btn.primary.bg', comp: 'button', ref: { '*': 's.interactive.primary' }, type: 'color' },
  { id: 'c.btn.primary.text', name: 'btn.primary.text', comp: 'button', ref: { '*': 's.text.inverse' }, type: 'color' },
  { id: 'c.btn.primary.hoverBg', name: 'btn.primary.hoverBg', comp: 'button', ref: { '*': 's.interactive.primaryHover' }, type: 'color' },
  { id: 'c.btn.danger.bg', name: 'btn.danger.bg', comp: 'button', ref: { '*': 's.interactive.danger' }, type: 'color' },
  { id: 'c.btn.danger.text', name: 'btn.danger.text', comp: 'button', ref: { '*': 's.text.inverse' }, type: 'color' },
  { id: 'c.btn.ghost.bg', name: 'btn.ghost.bg', comp: 'button', ref: { '*': 's.surface.primary' }, type: 'color' },
  { id: 'c.btn.ghost.text', name: 'btn.ghost.text', comp: 'button', ref: { '*': 's.text.secondary' }, type: 'color' },
  { id: 'c.btn.radius', name: 'btn.radius', comp: 'button', ref: { '*': 's.radius.control' }, type: 'radius' },
  { id: 'c.btn.paddingX', name: 'btn.paddingX', comp: 'button', ref: { '*': 's.gap.lg' }, type: 'spacing' },
  { id: 'c.btn.paddingY', name: 'btn.paddingY', comp: 'button', ref: { '*': 's.gap.sm' }, type: 'spacing' },
  { id: 'c.btn.fontSize', name: 'btn.fontSize', comp: 'button', ref: { '*': 's.fontSize.label' }, type: 'fontSize' },
  { id: 'c.card.bg', name: 'card.bg', comp: 'card', ref: { '*': 's.surface.primary' }, type: 'color' },
  { id: 'c.card.border', name: 'card.border', comp: 'card', ref: { '*': 's.border.default' }, type: 'color' },
  { id: 'c.card.radius', name: 'card.radius', comp: 'card', ref: { '*': 's.radius.card' }, type: 'radius' },
  { id: 'c.card.padding', name: 'card.padding', comp: 'card', ref: { '*': 's.padding.card' }, type: 'spacing' },
  { id: 'c.card.title.color', name: 'card.title.color', comp: 'card', ref: { '*': 's.text.primary' }, type: 'color' },
  { id: 'c.card.body.color', name: 'card.body.color', comp: 'card', ref: { '*': 's.text.secondary' }, type: 'color' },
  { id: 'c.input.bg', name: 'input.bg', comp: 'input', ref: { '*': 's.surface.primary' }, type: 'color' },
  { id: 'c.input.border', name: 'input.border', comp: 'input', ref: { '*': 's.border.default' }, type: 'color' },
  { id: 'c.input.focusBorder', name: 'input.focusBorder', comp: 'input', ref: { '*': 's.border.focus' }, type: 'color' },
  { id: 'c.input.text', name: 'input.text', comp: 'input', ref: { '*': 's.text.primary' }, type: 'color' },
  { id: 'c.input.placeholder', name: 'input.placeholder', comp: 'input', ref: { '*': 's.text.tertiary' }, type: 'color' },
  { id: 'c.input.radius', name: 'input.radius', comp: 'input', ref: { '*': 's.radius.control' }, type: 'radius' },
  { id: 'c.input.paddingX', name: 'input.paddingX', comp: 'input', ref: { '*': 's.gap.md' }, type: 'spacing' },
  { id: 'c.input.paddingY', name: 'input.paddingY', comp: 'input', ref: { '*': 's.gap.sm' }, type: 'spacing' },
  { id: 'c.input.fontSize', name: 'input.fontSize', comp: 'input', ref: { '*': 's.fontSize.body' }, type: 'fontSize' },
];

const VERSION_HISTORY: VersionEntry[] = [
  { user: 'JM', action: 'Added amber.400/500 primitives', time: '2 hours ago' },
  { user: 'AL', action: 'Mapped interactive.warning semantic', time: '3 hours ago' },
  { user: 'JM', action: 'Created input component tokens', time: '5 hours ago' },
  { user: 'SR', action: 'Updated dark theme surface refs', time: '1 day ago' },
  { user: 'AL', action: 'Initial token architecture setup', time: '2 days ago' },
];

createRoot(document.getElementById('root')!).render(
  <FigmaTokenExporter
    primitives={PRIMITIVES}
    semantics={SEMANTICS}
    components={COMPONENTS}
    versionHistory={VERSION_HISTORY}
    onTokenSelect={(id) => console.log('Selected:', id)}
  />,
);
