"""
Type definitions for server_provider_cache package.

Defines protocols and type aliases for the cache system.
"""

from typing import Any, Callable, Awaitable, Protocol, Optional, TypeVar

T = TypeVar("T")


class IBackend(Protocol):
    """Protocol for cache backend implementations."""

    async def get(self, key: str) -> Any | None: ...
    async def set(self, key: str, value: Any, ttl_ms: int) -> None: ...
    async def delete(self, key: str) -> None: ...
    async def clear(self) -> None: ...
    async def keys(self) -> list[str]: ...
    async def size(self) -> int: ...
    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...


class ICacheService(Protocol):
    """Protocol for cache service implementations."""

    @property
    def name(self) -> str: ...

    @property
    def default_ttl(self) -> int: ...

    @property
    def backend(self) -> str: ...

    async def get(self, key: str) -> Any | None: ...
    async def set(self, key: str, value: Any, ttl: Optional[int] = None) -> None: ...
    async def delete(self, key: str) -> None: ...
    async def clear(self) -> None: ...
    async def keys(self) -> list[str]: ...
    async def size(self) -> int: ...
    async def get_or_set(
        self,
        key: str,
        fetch_fn: Callable[[], Awaitable[T]],
        ttl: Optional[int] = None,
    ) -> T: ...
    async def destroy(self) -> None: ...


class ICacheFactory(Protocol):
    """Protocol for cache factory implementations."""

    def create(
        self,
        name: str,
        default_ttl: Optional[int] = None,
        backend: Optional[str] = None,
        namespace: Optional[str] = None,
    ) -> ICacheService: ...

    def get(self, name: str) -> ICacheService: ...
    def has(self, name: str) -> bool: ...
    async def destroy(self, name: str) -> None: ...
    async def destroy_all(self) -> None: ...
    def get_names(self) -> list[str]: ...
    def get_count(self) -> int: ...


# Type alias for fetch functions in get_or_set
FetchFn = Callable[[], Awaitable[Any]]


__all__ = [
    "IBackend",
    "ICacheService",
    "ICacheFactory",
    "FetchFn",
    "T",
]
