packages:
  - 'packages_mjs/*'
  - 'platform-core/fastify'
  - 'fastify_server'
  - 'fastify_apps/*/frontend'
  - 'fastify_apps/*/frontend-admin'
  - 'fastify_apps/*/frontend-components'
  - 'fastify_apps/*/backend'
  - 'fastify_apps/*/api'
  - 'fastify_apps/*/sequelize'
  - 'fastify_apps/*/widget/*'
  - 'fastify_apps/*/protobuf'
  - 'frontend_apps/*'
  - 'polyglot/*/mjs'
  - 'packages_mjs/auth_encoding'
  - 'packages_mjs/auth_config'
  - 'polyglot/gemini_openai_sdk/mjs/gemini-openai-sdk'
  - 'tools/package_mjs/cli-dev-runner'
  - 'how-to-get-started/4.database'
  - 'playwright/*'
  - 'frontend-components/*'
  - 'tools/*'
